
//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace global
[<assembly: Android.Runtime.ResourceDesignerAttribute("parser.Resource", IsApplication=true)>]
    do ()

namespace parser
    // Generated by F# CodeDom
    #nowarn "49" // uppercase argument names
    #nowarn "67" // this type test or downcast will always hold
    #nowarn "66" // this upcast is unnecessary - the types are identical
    #nowarn "58" // possible incorrect indentation..
    #nowarn "57" // do not use create_DelegateEvent
    #nowarn "51" // address-of operator can occur in the code
    #nowarn "1183" // unused 'this' reference
    
<<<<<<< HEAD
    exception ReturnException7568846aa483499e9474609595d89723 of obj
    exception ReturnNoneException7568846aa483499e9474609595d89723
    [<AutoOpen>]
    module FuncConvertFinalOverload7568846aa483499e9474609595d89723 =
=======
    exception ReturnException238d636cbe784080bf708fc47cebc2c9 of obj
    exception ReturnNoneException238d636cbe784080bf708fc47cebc2c9
    [<AutoOpen>]
    module FuncConvertFinalOverload238d636cbe784080bf708fc47cebc2c9 =
>>>>>>> 5e79e0865368629d2b9408a318d9baf45f4ad445
      // This extension member adds to the FuncConvert type and is the last resort member in the method overloading rules. 
      type global.Microsoft.FSharp.Core.FuncConvert with
          /// A utility function to convert function values from tupled to curried form
          static member FuncFromTupled (f:'T -> 'Res) = f
    
    type
        [<System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")>]
        
        (* partial *)Resource () =
            static do Android.Runtime.ResourceIdManager.UpdateIdValues()
            (* Member of type 'CodeTypeConstructor' is not supported by the CodeDOM provider and was omitted *)


    
    and
        
        (* partial *)Resource_Attribute () =
            static do Android.Runtime.ResourceIdManager.UpdateIdValues()
            (* Member of type 'CodeTypeConstructor' is not supported by the CodeDOM provider and was omitted *)


    
    and
        
        (* partial *)Resource_String () =
            static do Android.Runtime.ResourceIdManager.UpdateIdValues()
            // aapt resource value: 0x7f020000
            [<Microsoft.FSharp.Core.DefaultValueAttribute(false)>]
            static val mutable private library_name:int
            (* Member of type 'CodeTypeConstructor' is not supported by the CodeDOM provider and was omitted *)

